FROM node:12-buster

ENV PATH /app/node_modules/.bin:$PATH

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -yq google-chrome-stable \
    && apt-get install -yq jq nano bash-completion \
    && npm completion > /etc/bash_completion.d/npm

RUN npm install -g @angular/cli@^9
